# Generated by Django 6.0.6 on 2026-10-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('categoria_id', models.CharField(max_length=50)),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
